// ---------------------------------------------------------------------------
// Pull Request — proposal to merge fork changes (PRD Section 4.4)
// ---------------------------------------------------------------------------

import type { Timestamp } from './artifact';
import type { AgentType } from './agent';

// ---- PR Status & Review ----------------------------------------------------

export type PRStatus =
  | 'open'
  | 'approved'
  | 'merged'
  | 'rejected'
  | 'closed'
  | 'auto_merged';

export type ReviewAction =
  | 'approve'
  | 'reject'
  | 'request_changes'
  | 'comment';

// ---- Diff ------------------------------------------------------------------

export type DiffType =
  | 'text'
  | 'structured'
  | 'binary'
  | 'multimodal';

export interface DiffHunk {
  /** Starting line in the old version. */
  oldStart: number;
  /** Number of lines in the old version. */
  oldCount: number;
  /** Starting line in the new version. */
  newStart: number;
  /** Number of lines in the new version. */
  newCount: number;
  /** The actual diff content. */
  content: string;
  /** Section header / context. */
  header: string;
}

export interface Diff {
  type: DiffType;
  hunks: DiffHunk[];
  /** Always present, human-readable. */
  summary: string;
  addedLines: number;
  removedLines: number;
  /** Which sections changed. */
  changedSections: string[];
  /** TTS-ready summary for iOS review (generated by OpenAI TTS). */
  voiceNarration: string | null;
}

// ---- Source Ref (what informed the PR) -------------------------------------

export interface SourceRef {
  artifactId: string;
  ledgerId: string;
  /** Why this artifact is relevant. */
  relevance: string;
}

// ---- Pull Request ----------------------------------------------------------

export interface PullRequest {
  id: string;
  orgId: string;

  // -- References --
  forkId: string;
  /** The changed version. */
  sourceArtifactId: string;
  /** The original. */
  targetArtifactId: string;
  /** Where to merge. */
  targetLedgerId: string;

  // -- Content --
  /** Agent-generated summary. */
  title: string;
  /** Detailed explanation of changes. */
  description: string;
  diff: Diff;
  /** Human-readable change summary. */
  changeSummary: string;

  // -- Agent context --
  agentId: string;
  agentType: AgentType;
  /** 0.0 - 1.0 agent confidence. */
  confidence: number;
  /** Why this change matters. */
  justification: string;
  /** What data/artifacts informed this. */
  sourceRefs: SourceRef[];

  // -- Review --
  status: PRStatus;
  /** Who reviewed (user or auto). */
  reviewerId: string | null;
  reviewAction: ReviewAction | null;
  reviewComment: string | null;
  reviewedAt: Timestamp | null;

  // -- YOLO --
  /** Meets YOLO criteria. */
  autoMergeEligible: boolean;
  /** If auto-merged. */
  autoMergedAt: Timestamp | null;

  // -- Lifecycle --
  createdAt: Timestamp;
  updatedAt: Timestamp;
  mergedAt: Timestamp | null;
  closedAt: Timestamp | null;
}
