#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Lurk — Generate .env file from Google Cloud Secret Manager
# ---------------------------------------------------------------------------
# Run this once after cloning to set up local development:
#   chmod +x scripts/setup-local-env.sh
#   ./scripts/setup-local-env.sh
#
# Requires: gcloud CLI authenticated with access to lurk-a692c project
# ---------------------------------------------------------------------------

set -euo pipefail

PROJECT_ID="lurk-a692c"
ENV_FILE=".env"

echo "Fetching secrets from GCP Secret Manager (project: $PROJECT_ID)..."

ANTHROPIC_KEY=$(gcloud secrets versions access latest --secret=anthropic-api-key --project="$PROJECT_ID" 2>/dev/null) || {
  echo "WARNING: Could not fetch anthropic-api-key. Set ANTHROPIC_API_KEY manually in .env"
  ANTHROPIC_KEY=""
}

OPENAI_KEY=$(gcloud secrets versions access latest --secret=openai-api-key --project="$PROJECT_ID" 2>/dev/null) || {
  echo "WARNING: Could not fetch openai-api-key. Set OPENAI_API_KEY manually in .env"
  OPENAI_KEY=""
}

FIREBASE_CONFIG=$(gcloud secrets versions access latest --secret=firebase-client-config --project="$PROJECT_ID" 2>/dev/null) || {
  echo "WARNING: Could not fetch firebase-client-config."
  FIREBASE_CONFIG=""
}

NEXTAUTH_SECRET_VAL=$(gcloud secrets versions access latest --secret=nextauth-secret --project="$PROJECT_ID" 2>/dev/null) || {
  echo "WARNING: Could not fetch nextauth-secret. Generating random one."
  NEXTAUTH_SECRET_VAL=$(openssl rand -base64 32)
}

# Parse Firebase config JSON
if [ -n "$FIREBASE_CONFIG" ]; then
  FB_API_KEY=$(echo "$FIREBASE_CONFIG" | python3 -c "import sys,json; print(json.load(sys.stdin)['apiKey'])" 2>/dev/null || echo "")
  FB_AUTH_DOMAIN=$(echo "$FIREBASE_CONFIG" | python3 -c "import sys,json; print(json.load(sys.stdin)['authDomain'])" 2>/dev/null || echo "lurk-a692c.firebaseapp.com")
  FB_PROJECT_ID=$(echo "$FIREBASE_CONFIG" | python3 -c "import sys,json; print(json.load(sys.stdin)['projectId'])" 2>/dev/null || echo "lurk-a692c")
  FB_STORAGE_BUCKET=$(echo "$FIREBASE_CONFIG" | python3 -c "import sys,json; print(json.load(sys.stdin)['storageBucket'])" 2>/dev/null || echo "lurk-a692c.firebasestorage.app")
  FB_MESSAGING_SENDER_ID=$(echo "$FIREBASE_CONFIG" | python3 -c "import sys,json; print(json.load(sys.stdin)['messagingSenderId'])" 2>/dev/null || echo "")
  FB_APP_ID=$(echo "$FIREBASE_CONFIG" | python3 -c "import sys,json; print(json.load(sys.stdin)['appId'])" 2>/dev/null || echo "")
  FB_MEASUREMENT_ID=$(echo "$FIREBASE_CONFIG" | python3 -c "import sys,json; print(json.load(sys.stdin)['measurementId'])" 2>/dev/null || echo "")
else
  FB_API_KEY=""
  FB_AUTH_DOMAIN="lurk-a692c.firebaseapp.com"
  FB_PROJECT_ID="lurk-a692c"
  FB_STORAGE_BUCKET="lurk-a692c.firebasestorage.app"
  FB_MESSAGING_SENDER_ID=""
  FB_APP_ID=""
  FB_MEASUREMENT_ID=""
fi

cat > "$ENV_FILE" << ENVEOF
# ---------------------------------------------------------------------------
# Lurk Platform — Local Development Environment
# ---------------------------------------------------------------------------
# AUTO-GENERATED by scripts/setup-local-env.sh — do not commit this file.
# Secrets pulled from GCP Secret Manager (project: $PROJECT_ID)
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ---------------------------------------------------------------------------

# GCP / Firebase
GCP_PROJECT_ID=$PROJECT_ID
GOOGLE_CLOUD_PROJECT=$PROJECT_ID

# Firebase Client SDK
NEXT_PUBLIC_FIREBASE_API_KEY=$FB_API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$FB_AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_PROJECT_ID=$FB_PROJECT_ID
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$FB_STORAGE_BUCKET
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$FB_MESSAGING_SENDER_ID
NEXT_PUBLIC_FIREBASE_APP_ID=$FB_APP_ID
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=$FB_MEASUREMENT_ID

# Also set as non-NEXT_PUBLIC for API gateway to serve via /v1/policy/client-config
FIREBASE_AUTH_DOMAIN=$FB_AUTH_DOMAIN
FIREBASE_STORAGE_BUCKET=$FB_STORAGE_BUCKET

# LLM API Keys (from Secret Manager)
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
OPENAI_API_KEY=$OPENAI_KEY

# Service URLs (local development)
API_GATEWAY_URL=http://localhost:8080
AGENT_ORCHESTRATOR_URL=http://localhost:8082
LLM_GATEWAY_URL=http://localhost:8083
PII_SERVICE_URL=http://localhost:8084
MIGRATION_SERVICE_URL=http://localhost:8085
NOTIFICATION_SERVICE_URL=http://localhost:8086
TTS_SERVICE_URL=http://localhost:8087
AUDIT_SERVICE_URL=http://localhost:8088

# API Gateway
CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX_REQUESTS=1000

# Agent Orchestrator
AGENT_MAX_CONCURRENCY=5
AGENT_TIMEOUT_SECONDS=300

# LLM Gateway
LLM_DEFAULT_MODEL=claude-sonnet-4-20250514
LLM_MAX_TOKENS=128000
LLM_REQUEST_TIMEOUT=180

# PII Service
SPACY_MODEL=en_core_web_sm
PII_CONFIDENCE_THRESHOLD=0.7

# TTS Service
TTS_PROVIDER=openai
TTS_AUDIO_BUCKET=lurk-a692c-tts-audio

# Audit Service
AUDIT_RETENTION_DAYS=365

# Web Admin
NEXT_PUBLIC_API_URL=http://localhost:8080
NEXTAUTH_SECRET=$NEXTAUTH_SECRET_VAL
NEXTAUTH_URL=http://localhost:3000

# Chrome Extension (build-time vars)
VITE_FIREBASE_API_KEY=$FB_API_KEY
VITE_FIREBASE_AUTH_DOMAIN=$FB_AUTH_DOMAIN
VITE_FIREBASE_PROJECT_ID=$FB_PROJECT_ID
VITE_LURK_API_URL=http://localhost:8080
ENVEOF

echo ""
echo "✓ .env file created with $(grep -c '=' "$ENV_FILE") variables"
echo "✓ Secrets loaded from GCP Secret Manager"
echo ""
echo "Next steps:"
echo "  1. Review .env and fill in any empty values"
echo "  2. Run: docker compose up"
echo "  3. Or run services individually: npm run dev"
